[versions]
agp = "8.13.1"
kotlin = "2.0.21"
coreKtx = "1.13.1"
lifecycleRuntimeKtx = "2.8.4"
activityCompose = "1.9.3"
composeBom = "2024.09.00"
junit4 = "4.13.2"
androidxJunitExt = "1.1.5"
androidxTestRunner = "1.5.2"
espressoCore = "3.7.0"
coroutinesTest = "1.9.0"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidxLifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidxComposeUi = { group = "androidx.compose.ui", name = "ui" }
androidxComposeUiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidxComposeUiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidxComposeUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidxComposeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
androidxMaterialIconsExtended = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.6.7" }

androidxComposeUiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidxComposeUiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

junit = { group = "junit", name = "junit", version.ref = "junit4" }
kotlinxCoroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }

androidxTestRunner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidxTestExtJunit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunitExt" }
androidxEspressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

androidxNavigationCompose = { group = "androidx.navigation", name = "navigation-compose", version = "2.7.7" }